version: "3"
services:
  backend:
    container_name: itms-api
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - itms-network 

  db:
    container_name: oracle-itms-db
    image: gvenzl/oracle-xe:18.4.0-slim
    environment:
      - ORACLE_SID=ITMS_DB
      - ORACLE_PASSWORD=oracle
    ports:
      - "1521:1521"
    networks:
      - itms-network

networks:
  itms-network:
    driver: bridge