-- USERS
INSERT INTO USERS
(ID, FULLNAME, USERNAME, PASSWORD, SALT, ROLE)
VALUES(USERS_SEQUENCE.NEXTVAL, 'John Doe', 'admin', 'hndlbmkehjwHoNptg38zO5V82U5xozIkgGwxitI/AM8=', 'itmsystem', 'IT_SUPPORT');
