-- USERS
INSERT INTO USERS
(ID, FULLNAME, USERNAME, PASSWORD, SALT, ROLE)
VALUES(NEXTVAL('USERS_SEQUENCE'), 'John Doe', 'john.doe', 'hndlbmkehjwHoNptg38zO5V82U5xozIkgGwxitI/AM8=', 'itmsystem', 'IT_SUPPORT');
INSERT INTO USERS
(ID, FULLNAME, USERNAME, PASSWORD, SALT, ROLE)
VALUES(NEXTVAL('USERS_SEQUENCE'), 'Anna Doe', 'anna.doe', 'hndlbmkehjwHoNptg38zO5V82U5xozIkgGwxitI/AM8=', 'itmsystem', 'EMPLOYEE');

-- TICKETS
INSERT INTO TICKETS
(ID, TITLE, DESCRIPTION, CREATION_DATE, PRIORITY, CATEGORY, STATUS, EMPLOYEE_ID, USER_ID)
VALUES(NEXTVAL('TICKETS_SEQUENCE'), 'Network Issue', NULL, TIMESTAMP '2025-02-25 10:00:00.000000', 'HIGH', 'NETWORK', 'NEW', 2, NULL);

-- COMMENTS
INSERT INTO COMMENTS
(ID, COMMENT, CREATION_DATE, TICKET_ID, USER_ID)
VALUES(NEXTVAL('COMMENTS_SEQUENCE'), 'IT Support is working on it.', TIMESTAMP '2025-02-25 10:00:00.000000', 1, 1);

-- AUDIT_LOGS
INSERT INTO AUDIT_LOGS
(ID, ACTION, CREATION_DATE, TICKET_ID, USER_ID)
VALUES(NEXTVAL('AUDIT_LOGS_SEQUENCE'), 'Ticket Creation', TIMESTAMP '2025-02-25 10:00:00.000000', 1, 2);
INSERT INTO AUDIT_LOGS
(ID, ACTION, CREATION_DATE, TICKET_ID, USER_ID)
VALUES(NEXTVAL('AUDIT_LOGS_SEQUENCE'), 'Ticket Comment', TIMESTAMP '2025-02-25 10:00:00.000000', 1, 1);
