services:
  backend:
    container_name: itms-backend-api
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - itms-network 

  db:
    container_name: oracle-itms-hann-db
    image: oracledb19c/oracle.19.3.0-ee:oracle19.3.0-ee
    environment:
      - ORACLE_SID=ITMS_DB
      - ORACLE_PASSWORD=oracle
    ports:
      - "1521:1521"
    networks:
      - itms-network

networks:
  itms-network:
    driver: bridge
