-- TABLES CREATION
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

-- USERS
DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS (
    ID BIGINT PRIMARY KEY,
    FULLNAME VARCHAR(255) NOT NULL,
    USERNAME VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    SALT VARCHAR(255) NOT NULL,
    ROLE VARCHAR(20) NOT NULL,
    CONSTRAINT CHECK_ROLE_VALUE CHECK (ROLE IN ('EMPLOYEE', 'IT_SUPPORT')),
    CONSTRAINT UQ_USERNAME UNIQUE ("USERNAME")
);

CREATE SEQUENCE USERS_SEQUENCE START WITH 1 INCREMENT BY 1;

--------------------------------------------------------
--  DDL for Table TICKETS
--------------------------------------------------------

-- TICKETS
DROP TABLE IF EXISTS TICKETS;

CREATE TABLE TICKETS (
    ID BIGINT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255),
    CREATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIORITY VARCHAR(255) DEFAULT 'LOW',
    CATEGORY VARCHAR(255) NOT NULL,
    STATUS VARCHAR(30) DEFAULT 'NEW',
    EMPLOYEE_ID BIGINT NOT NULL,
    USER_ID BIGINT,
    CONSTRAINT CHECK_STATUS_VALUE CHECK (STATUS IN ('NEW', 'IN_PROGRESS', 'RESOLVED')),
    CONSTRAINT CHECK_PRIORITY_VALUE CHECK (PRIORITY IN ('LOW', 'MEDIUM', 'HIGH')),
    CONSTRAINT CHECK_CATEGORY_VALUE CHECK (CATEGORY IN ('NETWORK', 'HARDWARE', 'SOFTWARE', 'OTHER')),
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES USERS(ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

CREATE SEQUENCE TICKETS_SEQUENCE START WITH 1 INCREMENT BY 1;

--------------------------------------------------------
--  DDL for Table COMMENTS
--------------------------------------------------------

-- COMMENTS
DROP TABLE IF EXISTS COMMENTS;

CREATE TABLE COMMENTS (
    ID BIGINT PRIMARY KEY,
    COMMENT TEXT NOT NULL,
    CREATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TICKET_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,
    FOREIGN KEY (TICKET_ID) REFERENCES TICKETS(ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

CREATE SEQUENCE COMMENTS_SEQUENCE START WITH 1 INCREMENT BY 1;

--------------------------------------------------------
--  DDL for Table AUDIT_LOG
--------------------------------------------------------

-- AUDIT_LOG
CREATE TABLE AUDIT_LOGS (
    ID BIGINT PRIMARY KEY,
    ACTION VARCHAR(255),
    CREATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TICKET_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,
    FOREIGN KEY (TICKET_ID) REFERENCES TICKETS(ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

CREATE SEQUENCE AUDIT_LOGS_SEQUENCE START WITH 1 INCREMENT BY 1;
